[package]
name = "poseidon2-constants-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
p3-goldilocks = { git = "https://github.com/Plonky3/Plonky3", rev = "7895d23" }
p3-poseidon2 = { git = "https://github.com/Plonky3/Plonky3", rev = "7895d23" }
p3-field = { git = "https://github.com/Plonky3/Plonky3", rev = "7895d23" }
rand = "0.9"
rand_chacha = "0.9"

[workspace]
