[workspace]
members = [
    "crypto",
    "circuits/transaction",
    "circuits/block",
    "circuits/bench",
    "state/merkle",
    "consensus",
    "protocol/versioning",
    "network",
    "wallet",
    "wallet/bench",
    "tests",
]
resolver = "2"
