[package]
name = "recursion-spike"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14"
rand = "0.9"
p3-recursion = { git = "https://github.com/Plonky3/Plonky3-recursion.git" }
p3-circuit = { git = "https://github.com/Plonky3/Plonky3-recursion.git", package = "p3-circuit" }
p3-fri = { git = "https://github.com/Plonky3/Plonky3", rev = "7895d23" }
p3-uni-stark = { git = "https://github.com/Plonky3/Plonky3", rev = "7895d23" }
p3-field = { git = "https://github.com/Plonky3/Plonky3", rev = "7895d23" }
p3-baby-bear = { git = "https://github.com/Plonky3/Plonky3", rev = "7895d23" }
p3-challenger = { git = "https://github.com/Plonky3/Plonky3", rev = "7895d23" }
p3-commit = { git = "https://github.com/Plonky3/Plonky3", rev = "7895d23" }
p3-dft = { git = "https://github.com/Plonky3/Plonky3", rev = "7895d23" }
p3-merkle-tree = { git = "https://github.com/Plonky3/Plonky3", rev = "7895d23" }
p3-symmetric = { git = "https://github.com/Plonky3/Plonky3", rev = "7895d23" }
p3-matrix = { git = "https://github.com/Plonky3/Plonky3", rev = "7895d23" }
p3-poseidon2 = { git = "https://github.com/Plonky3/Plonky3", rev = "7895d23" }
p3-util = { git = "https://github.com/Plonky3/Plonky3", rev = "7895d23" }

[workspace]
