[package]
name = "state-da"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto = { package = "synthetic-crypto", path = "../../crypto" }
reed-solomon-erasure = "6"
thiserror = "1"
codec = { workspace = true }
rand = "0.8"
rand_chacha = "0.3"

[dev-dependencies]

[lints]
workspace = true
