[package]
name = "transaction-circuit"
version = "0.1.0"
edition = "2021"

[dependencies]
winterfell = "0.8"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
synthetic-crypto = { path = "../../crypto" }
hex = "0.4"

[dev-dependencies]
rand = { version = "0.8", features = ["std"] }

[features]
default = []
