[package]
name = "transaction-circuit"
version = "0.1.0"
edition = "2021"

[dependencies]
winterfell = "0.13"
winter-crypto = "0.13"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
synthetic-crypto = { path = "../../crypto" }
hex = "0.4"
protocol-versioning = { path = "../../protocol/versioning" }
miden-crypto = { version = "0.19", default-features = false, optional = true }
transaction-core = { path = "../transaction-core", features = ["serde", "stark-verify"] }

[dev-dependencies]
rand = { version = "0.8", features = ["std"] }
proptest = "1"

[features]
default = []
rpo-fiat-shamir = ["miden-crypto"]
legacy-proof = []
stark-fast = ["transaction-core/stark-fast"]

[lints]
workspace = true
