[package]
name = "consensus"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
bincode = "1"
crypto = { package = "synthetic-crypto", path = "../crypto" }
num-bigint = "0.4"
num-traits = "0.2"
sha2 = "0.10"
thiserror = "1"

[dev-dependencies]
network = { path = "../network" }
proptest = "1"
tokio = { version = "1", features = ["macros", "rt", "time", "sync"] }
