[package]
name = "state-merkle"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
transaction-core = { path = "../../circuits/transaction-core", features = ["plonky3"] }

[lints]
workspace = true
